// <auto-generated />
using System;
using AppQLKH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppQLKH.Migrations
{
    [DbContext(typeof(AppQLKHContext))]
    partial class AppQLKHContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppQLKH.Models.De_Tai", b =>
                {
                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("KinhPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDT")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaDT");

                    b.ToTable("De_Tai");
                });

            modelBuilder.Entity("AppQLKH.Models.Giang_Vien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGV");

                    b.ToTable("Giang_Vien");
                });

            modelBuilder.Entity("AppQLKH.Models.Tham_Gia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoGio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDT");

                    b.HasIndex("MaGV");

                    b.ToTable("Tham_Gia");
                });

            modelBuilder.Entity("AppQLKH.Models.Tham_Gia", b =>
                {
                    b.HasOne("AppQLKH.Models.De_Tai", "DeTai")
                        .WithMany()
                        .HasForeignKey("MaDT");

                    b.HasOne("AppQLKH.Models.Giang_Vien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGV");

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");
                });
#pragma warning restore 612, 618
        }
    }
}
